### ISSUE TITLE
Liopleurodon kills game

### ISSUE THREAD

**Issue by hornms0** [FossilsArcheologyRevival/FossilArcheology#380]
---- Minecraft Crash Report ----
// Sorry :(

Time: 2/22/15 6:52 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['starMUNCH'/1447226, l='MpServer', x=-1889.89, y=60.62, z=21954.58]]
    Chunk stats: MultiplayerChunkCache: 79, 79
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-1924,64,21966), Chunk: (at 12,4,14 in -121,1372; contains blocks -1936,0,21952 to -1921,255,21967), Region: (-4,42; contains chunks -128,1344 to -97,1375, blocks -2048,0,21504 to -1537,255,22015)
    Level time: 397145618 game time, 402172680 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 83 total; [EntityClientPlayerMP['starMUNCH'/1447226, l='MpServer', x=-1889.89, y=60.62, z=21954.58], EntityWaypointContainer['unknown'/9, l='MpServer', x=0.00, y=0.00, z=0.00], EntityDodo['Dodo'/1445174, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445172, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityPig['Pig'/1445170, l='MpServer', x=-1921.50, y=50.00, z=21944.47], EntityPig['Pig'/1445171, l='MpServer', x=-1921.53, y=50.00, z=21946.16], EntityStoneboard['entity.fossil.StoneBoard.name'/1445168, l='MpServer', x=-1935.06, y=66.00, z=21957.50], EntityStoneboard['entity.fossil.StoneBoard.name'/1445169, l='MpServer', x=-1935.06, y=67.00, z=21956.50], EntityDodo['Dodo'/1445182, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445180, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityDodo['Dodo'/1445178, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityDodo['Dodo'/1445176, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityCow['Cow'/1445158, l='MpServer', x=-1921.64, y=62.00, z=21955.26], EntityCow['Cow'/1445159, l='MpServer', x=-1920.45, y=62.00, z=21954.27], EntityCow['Cow'/1445157, l='MpServer', x=-1920.69, y=62.00, z=21957.75], EntityWolf['Wolf'/1445166, l='MpServer', x=-1926.69, y=64.00, z=21964.31], EntityWolf['Wolf'/1445167, l='MpServer', x=-1920.63, y=64.00, z=21964.44], EntityStoneboard['entity.fossil.StoneBoard.name'/1445164, l='MpServer', x=-1935.06, y=68.00, z=21955.00], EntityWolf['Wolf'/1445165, l='MpServer', x=-1923.00, y=64.00, z=21964.38], EntityPig['Pig'/1445162, l='MpServer', x=-1919.47, y=62.00, z=21960.47], EntityPig['Pig'/1445160, l='MpServer', x=-1921.53, y=62.00, z=21960.47], EntityChicken['Chicken'/1445161, l='MpServer', x=-1920.72, y=62.00, z=21960.53], EntityDodo['Dodo'/1445206, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityDodo['Dodo'/1445204, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityDodo['Dodo'/1445202, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445200, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityNautilus['Nautilus'/1447249, l='MpServer', x=-1856.94, y=29.00, z=21908.35], EntityDodo['Dodo'/1445214, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445212, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445210, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445208, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityDodo['Dodo'/1445190, l='MpServer', x=-1921.25, y=65.00, z=21948.25], EntityDodo['Dodo'/1445188, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445186, l='MpServer', x=-1921.75, y=65.00, z=21948.75], EntityDodo['Dodo'/1445184, l='MpServer', x=-1921.75, y=65.00, z=21948.75], EntityDodo['Dodo'/1445198, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445196, l='MpServer', x=-1921.75, y=65.00, z=21948.75], EntityDodo['Dodo'/1445194, l='MpServer', x=-1921.25, y=65.00, z=21948.25], EntityDodo['Dodo'/1445192, l='MpServer', x=-1921.25, y=65.00, z=21948.25], EntityWolf['Wolf'/1445239, l='MpServer', x=-1928.69, y=64.00, z=21969.22], EntityDodo['Dodo'/1445236, l='MpServer', x=-1921.25, y=65.00, z=21948.25], EntityDodo['Dodo'/1445234, l='MpServer', x=-1921.75, y=65.00, z=21948.25], EntityDodo['Dodo'/1445232, l='MpServer', x=-1921.25, y=65.00, z=21948.25], EntityVelociraptor['Velociraptor'/1445246, l='MpServer', x=-1934.16, y=64.00, z=21922.63], EntityVelociraptor['Velociraptor'/1445245, l='MpServer', x=-1937.69, y=63.00, z=21929.34], EntityVelociraptor['Velociraptor'/1445243, l='MpServer', x=-1934.31, y=63.00, z=21919.38], EntityBrachiosaurus['Jirard The Brachiosaur'/1445240, l='MpServer', x=-1925.91, y=64.00, z=21982.56], EntityTriceratops['Harold The Triceratops'/1445241, l='MpServer', x=-1924.88, y=64.00, z=21971.50], EntityDodo['Dodo'/1445222, l='MpServer', x=-1921.75, y=65.00, z=21948.75], EntityDodo['Dodo'/1445220, l='MpServer', x=-1921.75, y=65.00, z=21948.75], EntityDodo['Dodo'/1445218, l='MpServer', x=-1921.25, y=65.00, z=21948.25], EntityDodo['Dodo'/1445216, l='MpServer', x=-1921.25, y=65.00, z=21948.25], EntityDodo['Dodo'/1445230, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityDodo['Dodo'/1445228, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityTrail['unknown'/122, l='MpServer', x=-1889.89, y=60.62, z=21954.58], EntityOtherPlayerMP['mind_crap11'/1435979, l='MpServer', x=-1945.56, y=64.00, z=21947.34], EntityDodo['Dodo'/1445226, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntityDodo['Dodo'/1445224, l='MpServer', x=-1921.25, y=65.00, z=21948.75], EntitySkeleton['Skeleton'/1447574, l='MpServer', x=-1862.69, y=33.00, z=21961.84], EntityOtherPlayerMP['mind_crap11'/1435979, l='MpServer', x=-1942.16, y=64.00, z=21955.22], EntityMosasaurus['Mosasaurus'/1445271, l='MpServer', x=-1894.09, y=58.66, z=21937.81], EntitySkeleton['Skeleton'/1447575, l='MpServer', x=-1860.84, y=33.00, z=21963.84], EntitySpider['Spider'/1447572, l='MpServer', x=-1860.66, y=33.00, z=21959.09], EntitySkeleton['Skeleton'/1447573, l='MpServer', x=-1862.50, y=33.00, z=21958.50], EntityTerrorBird['Terror Bird'/1445269, l='MpServer', x=-1934.75, y=63.00, z=21908.41], EntitySpider['Spider'/1447570, l='MpServer', x=-1861.44, y=33.00, z=21960.75], EntitySpider['Spider'/1447571, l='MpServer', x=-1859.00, y=33.00, z=21963.81], EntityElasmotherium['Edward The Elasmotherium'/1445278, l='MpServer', x=-1915.31, y=64.00, z=22001.31], EntityGallimimus['Gallimimus'/1445277, l='MpServer', x=-1895.31, y=62.00, z=21985.53], EntitySpider['Spider'/1447579, l='MpServer', x=-1858.81, y=33.00, z=21956.00], EntityLiopleurodon['Leonardo The Liopluerodon'/1445272, l='MpServer', x=-1892.47, y=60.88, z=21954.19], EntitySpider['Spider'/1447576, l='MpServer', x=-1860.50, y=33.00, z=21954.50], EntityMammoth['Eguardo The Mammoth'/1445255, l='MpServer', x=-1925.69, y=64.00, z=21996.53], EntityPig['Pig'/1445250, l='MpServer', x=-1920.38, y=62.00, z=21961.66], EntityChicken['Chicken'/1445251, l='MpServer', x=-1919.16, y=62.00, z=21961.28], EntityStegosaurus['Tom The Stegosaur'/1445256, l='MpServer', x=-1905.38, y=65.00, z=21987.75], EntityStegosaurus['Sally The Stegosaur'/1445257, l='MpServer', x=-1910.44, y=65.00, z=21992.84], EntityCow['Cow'/1445305, l='MpServer', x=-1872.50, y=61.00, z=21974.25], EntitySnowman['Snow Golem'/1446319, l='MpServer', x=-1935.50, y=65.00, z=21951.50], EntityZombie['Zombie'/1445342, l='MpServer', x=-1856.03, y=12.00, z=21944.50], EntityCow['Cow'/1445343, l='MpServer', x=-1870.94, y=61.00, z=21975.97], EntityNautilus['Nautilus'/1445351, l='MpServer', x=-1865.78, y=29.38, z=21908.91], EntityItem['item.item.porkchopRaw'/1445869, l='MpServer', x=-1929.69, y=48.00, z=21947.69]]
    Retry entities: 0 total; []
    Server brand: cauldron,craftbukkit,mcpc,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 112561616 bytes (107 MB) / 339623936 bytes (323 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 Optifine OptiFine_1.7.10_HD_U_A4 17 mods loaded, 17 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1240} [Forge Mod Loader](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1240} [Minecraft Forge](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VeinMiner_coremod{null_build-null} [Core mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    lucky{5.0.0} [Lucky Block]([1-7-2]_Lucky_Block_v5-0-0%281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    walljump{1.2.1c} [WallJump]([1.7.10] [Forge] Wall Jump 1.2.1c by NukeDuck.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    craftguide{1.6.8.1} [CraftGuide](CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    fossil{1.7.10 Build 7.0.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.0.1 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{4.1.3} [iChunUtil](iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VeinMiner{0.21.0} [Vein Miner](VeinMiner-1.7.10_0.21.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VeinMinerModSupport{0.21.0} [Mod Support](VeinMiner-1.7.10_0.21.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    voxelmap{1.7.10} [VoxelMap No Radar](voxelmapNoRadar-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.7.10-Forge10.13.2.1240
    LWJGL: 2.9.1
    OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.3.12683 Compatibility Profile Context 13.302.1601.1001, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by hornms0** [comment]
This occured when i fed a baby liopleurodon and proceeded to check its dinopedia.
