### ISSUE TITLE
Dinopedia Causes crash on any Dinosaur on ATL Resonant Rise Pack

### ISSUE THREAD

**Issue by Lazylazzers7331** [FossilsArcheologyRevival/FossilArcheology#383]
I am running a server with my friend also on the server , and he can click on dinos fine with the dinopedia, however i cannot. When i click on any dino my game Crashes to desktop very annoying

Please help with soloution :-) 

thanks 

Error Log:
Unexpected error

java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by aziel13** [comment]
Im also having the same issue.  This is very similar to issue #145. The only difference sofar is that I am not flying at the time and that I dont have any voxel mods installed. I have also seen this crash when using the dinopedia on a pig that is impregnated. This might be a pack specific conflict.

**Comment by juniorjunior** [comment]
I get a similar crash when attempting to use the Dinopedia: http://pastebin.com/Gv5WsqCc

Let us hope that this can be resolved in a way that doesn't involve simply removing LiteLoader (if that is indeed the conflict).
